apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 2  # Number of Pods
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sample-container
          image: sampleimage:v1  # Replace with your actual image version
          ports:
            - containerPort: 8080
