apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: NodePort  # Exposes the service externally
  selector:
    app: sampleapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
